### ISSUE TITLE
variableDensMMS test

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/NaluRtest#18]
Stefan,

I am wondering if the `variableDensMMS` test can be split into a `variableDensNonIso` and `variableDensNonUniform` test since it appears to essentially be two tests? Or is there a reason I am unaware of that they should be considered a union?

**Comment by spdomin** [comment]
We can split this test if needed. The script-based approach was to simply to group by like testing. If this philosophy needs to be changed for Ctest naming, that is fine. Just rename the directory (two new ones) with the input file names.

**Comment by jrood-nrel** [comment]
Ok, great. That makes it straightforward. I will do that then, and close this.
