### ISSUE TITLE
Discussion of avoiding copies to runNaluRtest

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/NaluRtest#24]
One of the next things on my list regarding the tests, before I write any documentation on adding tests, I want to discuss, is the possibility of reorganizing how `runNaluRtest` is used.

My first thought is that we could create `runNaluRtest` in the `NaluRtest` repo directory and `.gitignore` everything in it. Then we run the tests in the `runNaluRtest` directory structure as normal, but giving relative paths to input files and meshes, etc. This would avoid the file copying, which is getting to be a large process. It would also simplify adding a test to CTest down to really just a single line if we don't have to describe the file copies as well.

My second thought is that we could run the tests directly in the test directories in `NaluRtest` with relative paths to the meshes. This has the possibility of polluting the `NaluRtest` directory, but I think maybe we could `.gitignore` the output files? I'm not sure if having git ignored output files in the `NaluRtest` directory after the tests run would be off-putting.

My third thought is we leave it as it is, which would suffice too.

For example, if I want to just run one test `ctest -R femHC`, I am really only allowed one script to run before any and all tests, so the preparation script erases `runNaluRtest` and sets up every test, just for this single test. Therefore it would be advantageous to avoid this setup cost, as well as having to describe the file copies required for each test in CTest. It would also avoid having to specify the directory for `runNaluRtest` at cmake configure time: `-DRUNNALURTEST_DIR`.

Tagging @sayerhs to ask for his input as well.

**Comment by spdomin** [comment]
Do you mean this:

My second thought is that we could run the tests directly in the test directories in NaluRtest

Or that:

My second thought is that we could run the tests directly in the test directories in Nalu

I see a push to have everything in the Nalu repos, e.g., docs, tests, etc., however, I think that either tagging or pinning is viable. At the very least, we need to be weary of the repos limitations of 1 gig.

What you propose above seems reasonable. Let's put this on a team meeting list to discuss.

**Comment by jrood-nrel** [comment]
I definitely mean NaluRtest and not the Nalu code repo. I agree with the idea behind keeping at least the meshes in a separate repo. I haven't thought about moving the test input and norms into the main Nalu repo, but that might not be a bad idea. I don't think we want the main Nalu repo to become a heavyweight object, so I think we can all agree no meshes there though.

At the moment I am leaning most towards having a directory inside the NaluRtest repo where we run the tests that is .gitignored, and all the test output can be confined there, and able to be easily erased at will without polluting NaluRtest. Though now I might put some thought into how the tests could look if moved into the Nalu repo while making NaluRtest a mesh repo.
